### ISSUE TITLE
KWIC Table is missing properties

### ISSUE THREAD

**Issue by lukas-moertl** [acdh-oeaw/corpsum-ts#12]
in the old application the KWIC search via the viewattrsx endpoint provided infos about the the region, and the date of the article. this information in the new endpoint is lost, but also set via
```
setrefs: ["=doc.id", "=doc.datum", "=doc.region", "=doc.ressort2", "=doc.docsrc_name"]
```
see https://noske-amc.acdh.oeaw.ac.at/openapi/#/Corpus%20Search/getConcordance
I don't know if those are not there anymore or there is a new param to get those

**Comment by hpreki** [comment]
In the current noske the refs (i.e. the Metadata-fields) you want to receive with each line in the concordance is passed as 
`refs` (the documentation in swagger seems to be completely bollocks: the description of `refs` seems to be a copy from another method). 

e.g.
```
refs==doc.id,=doc.bibl,=doc.autor,=doc.docsrc,=doc.region
```

The results will be revceived as follows - i.e. as ordered list with the values in the same order as they were passed in `refs=` 

```
Tbl_refs\": [\"APA_19860220_APA0004\", \"APA-Meldungen digital  vom 1986-02-20\", \"hs\", \"APA\", \"agesamt\"]
```

**Comment by lukas-moertl** [comment]
thanks!
