### ISSUE TITLE
KWIC view: "open" not functional yet

### ISSUE THREAD

**Issue by hpreki** [acdh-oeaw/corpsum-ts#14]
in KWIC view: pressing "open"-button just displays the doc.id + text "not loaded yet."

btw. in the NoSke there is a 2-step process to "open" the full document: first you only get a bigger context  plus a button "DISPLAY WHOLE DOCUMENT" at the bottom. 
APA is _very_ sensitive to people looking at "whole documents" (they want this especially monitored!). So mimicking the more restricted  NoSke - behaviour would be very nice

**Comment by lukas-moertl** [comment]
had a problem with subcorpus
