### ISSUE TITLE
KWIC: adapt / fine tune metadata that is displayed 

### ISSUE THREAD

**Issue by hpreki** [acdh-oeaw/corpsum-ts#17]
After solving the problem of  fetching metadata-info  for lines in KWIC (#12): fine tune the arrangement + selection of metadata fields to enhance readability: 
currently there are too many meta-data columns, so the actual search-results ("left" "word" "right") get crammed. 

Suggested steps: 

* move doc.id to the left - i.e. make it the 1st column
 - that's what people are used from NoSke
 - doc.id contains all info about docsrc and date

 
 * remove columns doc.docsrc, doc.date, topic
 * remove  column tokenid  unless you still need it for testing! The normal user does not need this info. 
 
 
methods to additionally "compactify" the display: 
 
 *  you can also shorten the display of the doc.id  -> in a perfect word make it fully visible on mouse over.  
 * taking  that further: on clicking on the docid - or on a "button" if that's more convenient -  issue a  `fullref`-call and display _all_ existing meta-data for that entry. in short: realise the feature #16

**Comment by ctot-nondef** [comment]
dependent on #22

**Comment by lukas-moertl** [comment]
(copied from doc, sorry for being in german)
* Die Default-Anordnung der Header in der Tabelle wird so angepasst, dass sie für den normalen Anwendungsfall passt
* Wenn auf die Detail-Ansicht geklickt wird, wird ein fullref-Request abgesetzt und die aufbereitete Antwort angezeigt

**Comment by ctot-nondef** [comment]
additional tasks für @ctot-nondef und @hpreki : 

* compile translationlist for structures and attribute codes

**Comment by ctot-nondef** [comment]
for now, no visualization in table needed, downloaded docs are sufficient
