### ISSUE TITLE
Desiderate: offer functionality of NoSke's "View Options"

### ISSUE THREAD

**Issue by hpreki** [acdh-oeaw/corpsum-ts#18]
In NoSke you can use "View Options" - for selecting + deselecting which information should be displayed in the KWIC view. 
Offer the same functionality - i.e. allow the user to specify: 

* metadata  which should be displayed (  e.g. #12  )
* annotation on the found words which should be displayed ( e.g. lemma, PoS ) 
* structures which should be displayed ( e.g. `<s>` or `<p>` )

**Comment by ctot-nondef** [comment]
dependent on #22

**Comment by lukas-moertl** [comment]
(copied from doc, sorry for being in german)
->  In der KWIC-Ansicht ist es möglich, die Metadaten auszuwählen, die angezeigt werden sollen.

**Comment by ctot-nondef** [comment]
- [ ] the set of displayed columns should be adjustable to the available line details per item
- [ ] the set of selectable structures is incomplete - all subprops of doc are mssing
