### ISSUE TITLE
Wrong counts in "Word Form Frquencies" 

### ISSUE THREAD

**Issue by hpreki** [acdh-oeaw/corpsum-ts#21]
might be just a variant of bug #20 

When you issue several identical search queries using different SUBCORPORA only the results of the 1st search is used.  

corpus amc_4.2: 

1. word-search for "Kuckuck"  - without any subkorpus selected 

2.  word-search for "Kuckuck"  - with "AustriazismenSFB"  selected  
3.  word-search for "Kuckuck"  - without "kino01"  selected 

Result: counts are identical! 

![image](https://github.com/acdh-oeaw/corpsum-ts/assets/8236186/91a62cc6-f8a4-4083-9595-91cd9f31404f)

in the yearly-query the *huge* differences between the subcorpora is correctly reflected, though: 
![image](https://github.com/acdh-oeaw/corpsum-ts/assets/8236186/b5b1d75d-0b0d-4466-bf24-6b7a5fe5825e)

**Comment by lukas-moertl** [comment]
Should be fixed, please confirm @hpreki

**Comment by hpreki** [comment]
looks good - issue closed
