### ISSUE TITLE
`structctx` (full document view): wrong parameter-syntax

### ISSUE THREAD

**Issue by hpreki** [acdh-oeaw/corpsum-ts#24]
Christoph noticed: 

* make a query in `wrdiarium02.1`
* in the concordance select a hit-line and press "Open" to see the full document

=> the result is bonkers: a document is displayed, but it's from the **wrong corpus** (amc_4.1)

reason: wrong syntax wenn passing the parameters
current call: 
https://noskecrystal5corpsum.acdh-dev.oeaw.ac.at/run.cgi/structctx?q=corpname=wrdiarium02.1;pos=439874;struct=doc;format=json

problem: the "q="  needs  to be removed ! 
structctx? **q=** corpname=wrdiarium02.1;...

*Fun fact*: the wrong syntax prevents the correct detection of the 1st  parameter:  `q=xxxx=yyyy;` is not correctly parsed by the backend, but it issues no error but just applies some "default"  setting (in our case: amc_4.2). It took us some time to spot that error :-(

**Comment by hpreki** [comment]
**Nachtrag**: Beispiel für korrekten Aufruf aus der NoSke

(Reihenfolge der Parameter ist unwichtig) 

`structctx?pos=1156&corpname=amc_4.2&struct=doc`

**Comment by lukas-moertl** [comment]
solved, but not pretty. @hpreki you can add the correct request, than i will update it

**Comment by ctot-nondef** [comment]
all info should already be in this issue, please let us know if any more should be required
