### ISSUE TITLE
severe! bug: `freqml`: parameter `corpname` is missing

### ISSUE THREAD

**Issue by hpreki** [acdh-oeaw/corpsum-ts#25]
`freqml`: the parameter `corpname`  is missing in the API-call!!!! 

Not a "fun" fact anymore: the backend does not complain, but uses a default-corpus instead!

This affects frequencies per `doc.region` and frequencies per `doc.docsrc`

(frequencies per doc.year use `freqtt` and there the `corpname`  is correctly set)

That's the reason we get results for doc.region in the wrdiarium: it's not because there is some cashing or mis-handling of empty results, but the backend is never told to use `wrdiarium` but consults a default-corpus (which is SOME of the amc-corpora)

**Comment by lukas-moertl** [comment]
should be fixed
