### ISSUE TITLE
Display of relative and absolute numbers in mouse-overs

### ISSUE THREAD

**Issue by AgnesKim-oeaw** [acdh-oeaw/corpsum-ts#36]
Please add what the count in all the mouseovers pertains to (_Belege/Treffer_ or _Belege/Treffer p.m.w_, ...), e.g.:

![grafik](https://github.com/acdh-oeaw/corpsum-ts/assets/157716852/d6e626fc-8cc3-4aac-9bdf-fd5b3171ca6a)

**Comment by ctot-nondef** [comment]
this is an easy fix for the online version

adjusting the downloadable images accordingly may require more work
