### ISSUE TITLE
Adjustments in Word Form frequency charts

### ISSUE THREAD

**Issue by AgnesKim-oeaw** [acdh-oeaw/corpsum-ts#37]
In order to be able to explore very small values it would be very good to

- be able to **scroll into the chart**
- see the **mouse over** even when moving over the label and not only when moving over the bar

**Comment by ctot-nondef** [comment]
- [ ] make value card appear on hover over label as well (helpfull for small result values where the bar is very small)

**Comment by ctot-nondef** [comment]
info displayed in separate table, highcharts behaviour not adjustable as is
