### ISSUE TITLE
Information on sources in Media source charts

### ISSUE THREAD

**Issue by AgnesKim-oeaw** [acdh-oeaw/corpsum-ts#38]
It would be helpful if certain information on the media sources could be accessed directly form the Media Soruces chart, e.g., by in a mouse over. Most important is the source's full name because some abbreviations are not even clear to Austrians in some cases, e.g. "MWVOLL".

![grafik](https://github.com/acdh-oeaw/corpsum-ts/assets/157716852/1a05e57f-6be8-4474-8ed8-6e631dc89da2)

**Comment by hpreki** [comment]
The "longname" of each media is stored in the attribute `doc.docsrc_name`  which could be displayed on mouse-over. 
In addition `doc.mediatype` could be displayed ( `print, agentur, tv` and starting 2024 : `radio, www`)
