### ISSUE TITLE
Possiblity to restrict the search according to metadata

### ISSUE THREAD

**Issue by AgnesKim-oeaw** [acdh-oeaw/corpsum-ts#39]
It would be helpful to have the possibility to restrict the search according to the metadata such as

- time
- area
- source

**Comment by hpreki** [comment]
I second this. 
It would mean to mimic  the "Texttype"-Filtering available in NoSke 

FYI I usually tackle this issue (in the NoSke) by 
* writing the restrictions into a CQL ( e.g. `<doc region="awest" & year="20.."/>`) 
* and/or using sub-Corpora: an idea was. that until corpsum has "full" cabilities to create + delete sub-korpora users should be able to create+manage their sub-corpora in the NoSke and then re-use them in corpsum.  
(requires further testing -> separate issue)

**Comment by ctot-nondef** [comment]
ticket for GUI support #58
