### ISSUE TITLE
Download of KWICs or link to NoSke version?

### ISSUE THREAD

**Issue by AgnesKim-oeaw** [acdh-oeaw/corpsum-ts#40]
Currently it is not possible to download the KWICs, which is of course very helpful for corpus studies. If that is not possible due to copyright, a link to the NoSke version (KWIC display, with preset search of course)  would be helpful (that would be good anyways).

**Comment by ctot-nondef** [comment]
@hpreki can you answer this? thank you!

**Comment by hpreki** [comment]
I would support this feature request.
It's a feature that exists in the NoSke - I only now realised it's not in Corpsum ... and actually never was. 

A quick inspection of the NoSke behaviour: 
* as far as I can see the "Download" of an existing KWIC (i.e. result of an `concordance`-call) is re-issued with a `pagesize=0` 
(which probably should mean: no paging) 
* but this seems to work very unstable: even for moderate-sized KWIC lists (amc_4.2: Krokodil 30k hits) the query goes on "forever" until some time-out is reached :-(  => requires further testing!

**Comment by ctot-nondef** [comment]
#56

**Comment by ctot-nondef** [comment]
#57 - issue for NoSke Link
