### ISSUE TITLE
Possiblity to compare Regional and Source Medium frequency of more than one query within single charts

### ISSUE THREAD

**Issue by AgnesKim-oeaw** [acdh-oeaw/corpsum-ts#41]
Currently only relative and absolute frequencies are displayed of single queries are displayed on the map (for Regional frequencies) or with single bars (for Source Medium frequencies). It would be a nice asset to be able to view them in relation to each other, i.e. as a pie chart for the Regional frequencies or within a scaled bar chart for the Source Medium frequencies as it is possible within the **Word at a Glance (WaG) app of the Czech national corpus**:  https://www.korpus.cz/slovo-v-kostce/compare/cs/kluk--chlap--chlapec--hoch

![grafik](https://github.com/acdh-oeaw/corpsum-ts/assets/157716852/9f9d223d-c918-46a3-abbf-4751338b722e)

**Comment by ctot-nondef** [comment]
* die neuen/alternativen visualisierungen sollten die bereits bestehenden nicht ersetzen, stattdessen sollte es pro Ergebnistyp (search dimension) die möglichkeit geben mehrere visualisierungstypen auswählen zu können (das würde auch zukünftig das umsetzen anderer visualisierungen erleichtern)

* wichtig ist, dass es dann pro visualisierungstyp unterschiedliche optionen gibt (für einen stacked bar chart bzw pie chart macht bspw macht der switch absolut/relativ wahrscheinlich keinen sinn)

**Comment by ctot-nondef** [comment]
implemented and deployed on dev - feeback pending

**Comment by ctot-nondef** [comment]
- [ ] move pie chart asuedost to the left (more in the middle of the region)
- [ ] display values on hiver in pie charts as percentages of pie (not realtive to corpus as now)

**Comment by ctot-nondef** [comment]
legend/info displayed in separate component
