### ISSUE TITLE
Idea: display collocations and similarly used words

### ISSUE THREAD

**Issue by AgnesKim-oeaw** [acdh-oeaw/corpsum-ts#42]
See the according functions of the **Word at a Glance app of the Czech National Corpus**:

https://www.korpus.cz/slovo-v-kostce/compare/cs/kluk--chlap--chlapec--hoch

**Comment by hpreki** [comment]
This functionality (Noske: `collx` ) _was_ already available in the original corpsum and did it not make it into the current version. 
cf #6

**Comment by AgnesKim-oeaw** [comment]
Ah, I see. Was not aware of that.

**Comment by ctot-nondef** [comment]
--> possibly to resolved via a link button  as proposed in #57

**Comment by lukas-moertl** [comment]
(copied from doc, sorry for being in german)

Es werden 2 neue ‘Search Dimensions’ hinzugefügt.
### Collocations
Eigener Request, um die Collocations der Query zu erhalten
Verarbeitung der Ergebnisse
Display-Komponente, die diese Ergebnisse anzeigt
### Similarly used words
Eigener Request, um ähnliche Worte der Query zu erhalten
Verarbeitung der Ergebnisse
Display-Komponente, die diese Ergebnisse anzeigt:
Das könnte als Wortwolke wie hier umgesetzt werden
### Erweiterung der Yearly Frequency Ansicht
Im Yearly-Frequency-Graph kann auf einen Datenpunkt geklickt werden.
Es öffnet sich ein Popup, das eine Collx-Request für dieses Jahr absendet und die Ergebnisse präsentiert. Hier muss noch definiert werden, was genau angezeigt werden soll.

**Comment by ctot-nondef** [comment]
betreffs der erweiterung der Yearly Frequency Ansicht: da diese queries lt hannes recht costly sein können, ist wahrscheinlich ein popup keine gute variante, stattdessen würde ich vorschlagen dass es entweder 
* eine extra search dimension "collocations by year" gibt zu der dann navigiert werden kann
* oder die collocations search dimension generell einen optionalen filter nach jahren bekommt

**Comment by ctot-nondef** [comment]
https://github.com/czcorpus/kontext

**Comment by lukas-moertl** [comment]
similar words in czcorpus: https://utils.korpus.cz/wsserver/corpora/syn_v8/similarWords/nce/koule/N?limit=10&minScore=0.6
-> how to do it in our instance?

**Comment by hpreki** [comment]
**attention**: 

the functionality to provide "Similar Words" is only offered by the SketchEngine ( API-call: `/search/thes` ), i.e. this is not available in the **No**Ske. Therefore the  call https://utils.korpus.cz/wsserver/corpora/syn_v8/similarWords/nce/koule/N?limit=10&minScore=0.6  either accesses a SketchEngine as back-end, or some other service.

**Comment by hpreki** [comment]
Status 2024-08-06:
because "similar words"  is not available in the NoSke (`/search/thes`) , this functionality for now will  not be offfered by corpsum. 
In the future a web-service for providing lists of similar words might be made available
 by Stefan Resch.

**Comment by ctot-nondef** [comment]
colocations implemented using `/search/collx` endpoint - feedback pending

**Comment by ctot-nondef** [comment]
Parameters currently set for the request:

| Attribute | Default Value | Description                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
|-----------|---------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| cattr     | lemma         | The (positional attribute)[https://www.sketchengine.eu/my_keywords/positional-attribute/] (lemma, word form etc.) used in the computation.                                                                                                                                                                                                                                                                                                                            |
| ctow      | 3             | The right boundary of the window in which the collocations should be identified. Defined by the token position left or right of KWIC.                                                                                                                                                                                                                                                                                                                                 |
| cminfreq  | 9             | The minimum frequency of the token in the corpus.                                                                                                                                                                                                                                                                                                                                                                                                                     |
| cminbgr   | 9             | The minimum frequency of the token in the window defined by `cfromw` and `ctow`.                                                                                                                                                                                                                                                                                                                                                                                      |
| cbgrfns   | dmt           | Defines the types of statistics (association measures) to be computed. \n\n `t` -> T-score \n\n `m` -> MI \n\n `3` -> MI3 \n\n `l` -> log likelihood \n\n `s` -> min. sensitivity \n\n `p` -> MI.log_f \n\n `r` -> relative freq. \n\n `f` -> absolute freq. \n\n `d` -> logDice. \n\n  To send one value just type the value for example `t`. If you need to send more values write it as `[ \" t \" , \" m \" , \" d \" , \" 3 \" , \" l \" , \" s \" , \" p \" ]`. |
| csortfn   | d             | Function according to which the result is sorted.                                                                                                                                                                                                                                                                                                                                                                                                                     |

**Comment by ctot-nondef** [comment]
params to expose for adjustment to user:
`ctow` , `cfromw` (no doc available?), `cminfreq` (should be an absolute value), `cminbgr` (more important than cminfreq)  - set range to 5 - 25 to start - pending adjustemnt)
`cmaxitems` (currently not in table) - default range 10 - 50

**Comment by ctot-nondef** [comment]
exposure of `cattr` requires a separate ticket

**Comment by ctot-nondef** [comment]
cattr exposed
