### ISSUE TITLE
No KWICs displayed for phrase searches

### ISSUE THREAD

**Issue by AgnesKim-oeaw** [acdh-oeaw/corpsum-ts#43]
See screenshot

![grafik](https://github.com/acdh-oeaw/corpsum-ts/assets/157716852/18462d2c-513c-4a4d-8d06-96a7c4ffc1a4)

**Comment by hpreki** [comment]
Der call wird falsch zusammengebaut: 

dzt. in corpsum: 

https://noskecrystal5corpsum.acdh-dev.oeaw.ac.at/run.cgi/concordance?q=aword,[word="dieses+haus"];corpname=amc4_demo;viewmode=kwic;attrs=word;ctxattrs=word;setattrs=word;allpos=kw;refs==doc.id,=doc.datum,=doc.region,=doc.ressort2,=doc.docsrc_name;pagesize=1000;newctxsize=30;async=0;format=json


Die verwendete option `q[...]` schickt eine CQL-query(!)    `[word="dieses+haus"]` - d.h. es sucht ein WORT das "dieses+haus" lautet ! Folgerichtig ist das Ergebnis leer. 

Fixes:  cf. Swagger! 
* entweder `json=...` - syntax verwenden: völlig ident wie bei `freqml` - also `json={"concordance_query":{"phrase":"das+Haus","queryselector":"phraserow"}} ` 

* oder - wenn es die "nicht-json-syntax" sein soll: 
`concordance_query[queryselector]=phraserow&concordance_query[phrase]=ein Haus&`

**Comment by hpreki** [comment]
Fix should be easy:  _are_ correctly composed (using the  `json=...` syntax) when issuing frequeny-queries (method: `freqsml`). Just use the very same calls for `concordance`
