### ISSUE TITLE
Time series per month `yymm`

### ISSUE THREAD

**Issue by hpreki** [acdh-oeaw/corpsum-ts#54]
## Time series per month

Bisweilen wird Zeitverlauf auch in Monaten ausgewertet ( 'doc.yymm`) -> lt. Theresa: nice to have, aber keine prio

**Comment by lukas-moertl** [comment]
needs more clarification

**Comment by hpreki** [comment]
Other than #53 this _can_ be realized by a simple request: just like for the "per year" - analysis: use `freqml`  but instead of `doc.year` use `doc.yymm` 
`doc.yymm` holds the info about the month : format is `yyyy-mm` i.e. a document from february 2024 would have a `doc.yymm="2024-02"`. 
IMO this would be a very "cheap" enhancement.
