### ISSUE TITLE
create facetting gui based on corpusInfo

### ISSUE THREAD

**Issue by ctot-nondef** [acdh-oeaw/corpsum-ts#58]
the corpusInfo object delivers all Info required to build a [facetting interface ](https://noskecrystal5corpsum.minerva.arz.oeaw.ac.at/crystal/#concordance?corpname=amc_4.3&tab=advanced&keyword=Virus&attrs=word&viewmode=kwic&attr_allpos=all&refs_up=0&shorten_refs=1&glue=1&gdexcnt=300&show_gdex_scores=0&itemsPerPage=20&structs=s%2Cg&refs=%3Ddoc.id&default_attr=lemma&showresults=1&tts=%7B%22doc.region%22%3A%5B%22aost%22%5D%2C%22doc.year%22%3A%5B%221986%22%2C%221987%22%2C%221989%22%5D%7D&showTBL=0&tbl_template=&gdexconf=&f_tab=basic&f_showrelfrq=1&f_showperc=0&f_showreldens=0&f_showreltt=0&c_customrange=0&t_attr=doc.year&t_absfrq=1&operations=%5B%7B%22name%22%3A%22iquery%22%2C%22arg%22%3A%22Virus%22%2C%22query%22%3A%7B%22queryselector%22%3A%22iqueryrow%22%2C%22iquery%22%3A%22Virus%22%2C%22sca_doc.region%22%3A%5B%22aost%22%5D%2C%22sca_doc.year%22%3A%5B%221986%22%2C%221987%22%2C%221989%22%5D%7D%2C%22id%22%3A1209%7D%5D) as provided by noske

**Comment by ctot-nondef** [comment]
time
area
source

as initial facets req by user

**Comment by lukas-moertl** [comment]
(copied from doc, sorry for being in german)

Generell ist pro Query eine feinere Filterung möglich. Dafür gibt es Attribute, die je nach Corpus (evt. per Subcorpus) definiert sind, nach denen man filtern kann.
-> Es wird dynamisch je nach Ergebnis der corp_info abfrage eine Facettierungs-Möglichkeit angezeigt, die per Query einstellbar ist.

**Comment by ctot-nondef** [comment]
implemented and deployed on dev - feedback pending
