### ISSUE TITLE
KWIC: only 1st word of  multi-word hits is displayed

### ISSUE THREAD

**Issue by hpreki** [acdh-oeaw/corpsum-ts#59]
it is common to have CQL searches which search multiple-words. 

e.g. try:
`<doc> [] [] [] []`  => returns the 1st 4 words (token) at the beginning of a document
or 
`[word="ist"] [word="ein"]  []?  [word="Problem"] `

corpsum displays the left + right context correcty, but only the 1st word of the multi-word kwic.

Solution: 
`concordance` returns "Lines:" with "Kwic", "Left" and "Right": "Kwic" is a List! Display all the elements of this list and not just the 1st element!

**Comment by ctot-nondef** [comment]
the search is correctly submitted but the result table only displays the first token
