### ISSUE TITLE
provide `collocations` (cf. `collx`) => Wunsch-Feature

### ISSUE THREAD

**Issue by hpreki** [acdh-oeaw/corpsum-ts#6]
**Background:** it is a typical effect in the per-year plot, that the plot shows some interesting "bumps". 
It is obvious, that users would like to have a *closer look* in order to find out, what actually is *behind* these  "bumps". 

## Asil's solution: Collocations (per year) 

In Asils version:
In the frequency-per-year graph: when you clicked on a data point (i.e. a number of hits for a specific year) you would get a _collocation analysis_ specificly for that year. 

* pro: very powerful and compact representation 
* con: potentially too costly (performance) => takes a few seconds per year.  potentially *too* compact? 

Look e.g. for mentions of  `collx` in the code. 
  
Sample call from NoSke :
`https://noskecrystal5corpsum.minerva.arz.oeaw.ac.at/bonito/run.cgi/collx?corpname=amc4_demo&format=json&cmaxitems=2000&collpage=1&cattr=lemma&cfromw=-3&ctow=3&cminfreq=5&cminbgr=3&csortfn=d&json={"concordance_query":[{"queryselector":"iqueryrow","iquery":"Haus"}],"cbgrfns":["t","m","d"]}`

* Asil obviously issued a `colllx` with a `query` that was modified to only query 1 year - i.e. he had to add something llke e.g. `within <doc year="2010"/>`. 
* probably he looped over all years - and issued a separate `collx` for each year - or he issued the `collx- request on a "per-click" basis
* `collx` is possibly is a possibly costly query -  so it should _not_ be called by default and might be adorned with a _warning_ 
 
 ## Possible alternative: show Concordances (= KWIC)
 
 Instead of offering `collx` for the year in focus (i.e. find a set of  words which are somehow "attached" to your search-term in this specific year) display a KWIC which is filtered down to that year - i.e. when you click on a year in the graph the KWIC is narrowed down to just that year. Also a random selection of e.g. 100 hits could be used?

**Comment by hpreki** [comment]
Demand for collocations from end-user - cf. #42

**Comment by ctot-nondef** [comment]
related to #42
