### ISSUE TITLE
Word freqency chart: display all results in same scale

### ISSUE THREAD

**Issue by hpreki** [acdh-oeaw/corpsum-ts#63]
In the word-frequency chart each word now is dsiplayed in its "optimal" scale. 
That's great to aktually see very small numbers, but makes it less convenient to compare results between different words.  

Cf. Example with "Kasachstan" vs. "Kirgisien"  
![Screenshot from 2024-10-10 12-04-22](https://github.com/user-attachments/assets/2d95ee92-d1bd-492f-8564-cba83c6ae85a)

Nice to have: an option to display all charts in the same scale

possibly related to #37 => this issue deals with scaling iussues in  word-frequency charts

**Comment by ctot-nondef** [comment]
scaling not adjustable at will in highcharts, value display issues resolved in #37
