### ISSUE TITLE
search  [word="Hund"] and  [lemma="Hund"]: only 1 result! 

### ISSUE THREAD

**Issue by hpreki** [acdh-oeaw/corpsum-ts#7]
Steps for reproducing: 
use 2 or more searches which contain the same basic search string: 

e.g. `[word="Hund"]` vs. `[lemma="Hund"]` or [word="Hund"] in subkorpus `kino01`

Effect: 
* Differences in absolute counts:  
* per-year-view: correct
- [ ] per-source-view and per-region-view: results for all 3 searches are identical - both in the plots and in the data-view
 
Hypothesis: possibly confusion because same search-term ("Hund")  was used and results might be strored under that one term?

**Comment by lukas-moertl** [comment]
current query (prob. wrong ): ```{ concordance_query: [{ queryselector: "iqueryrow", iquery: query.userInput }] }```
