### ISSUE TITLE
Search does not terminate properly when there are NO hits

### ISSUE THREAD

**Issue by hpreki** [acdh-oeaw/corpsum-ts#8]
Try e.g. 

in `kino01`- subkopus: 
`[lemma="Katze"] within <doc docsrc="FALTER"/>`

The correct result is: 0 hits.  But the search-progress-indicator goes on and on, and there is no way to stop and or delete the result. 

Problem is exagerated due to the problem, that subsequent searches which also use "Katze" are ignored - i.e. 
when I relaunched the search `[lemma="Katze"] within <doc docsrc="FALTER"/>` for the WHOLE corpus - the results for "per year" are o.k. but for "per region" and "per source" are 0  - and also cannot be deleted.

**Comment by ctot-nondef** [comment]
=> implement proper 0 result view / flow

**Comment by ctot-nondef** [comment]
=> keep delete button visible for long queries

**Comment by lukas-moertl** [comment]
fixed in next version
