### ISSUE TITLE
Strange duplication in search -results

### ISSUE THREAD

**Issue by hpreki** [acdh-oeaw/corpsum-ts#9]
Searched ` [lemma="Kuh"] `

Result-csv:  Note that the results are repeated in the csv - and also in the bar-plots!

"Category","relative value"
"Kühe",5.6324902097211575
"Kuh",5.629138324544282
"Kühen",1.5310176582903474
"KUH",0.02778536396620726
"kuh",0.022933951210202818
"KÜHE",0.011555183109756034
"kühe",0.003087262662911918
"KÜHEN",0.0017641500930925245
"KuH",0.0005292450279277573
"KüHE",0.00017641500930925245
"KÜhe",0.00008820750465462622
"kühen",0.00008820750465462622
"Kühe",5.6324902097211575   <==== starts to repeat!!!
"Kuh",5.629138324544282
"Kühen",1.5310176582903474
"KUH",0.02778536396620726
"kuh",0.022933951210202818
"KÜHE",0.011555183109756034
"kühe",0.003087262662911918
"KÜHEN",0.0017641500930925245
"KuH",0.0005292450279277573
"KüHE",0.00017641500930925245
"KÜhe",0.00008820750465462622
"kühen",0.00008820750465462622

**Comment by lukas-moertl** [comment]
I can also not reproduce it. will close it for now. feel free to reopen.
